services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - nebula-data:/etc/nebula
    environment:
      - SECRET_KEY=change-this-in-production
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  nebula-data: